spring:
  datasource:
    url: jdbc:mariadb://localhost:3306/qsl?useUnicode=true&characterEncoding=utf8&serverTimeZone=Asia/Seoul&allowPublicKeyRetrieval=true&useSSL=false
    driver-class-name: org.mariadb.jdbc.Driver
    username: root
    password: rlaclgns5628

  jpa:
    hibernate:
      ddl-auto: update

  output:
    ansi:
      enabled: always