spring:
  datasource:
    url: jdbc:mariadb://localhost:3306/qsl?useUnicode=true&characterEncoding=utf8&serverTimeZone=Asia/Seoul&allowPublicKeyRetrieval=true&useSSL=false
    driver-class-name: org.mariadb.jdbc.Driver
    username: root
    password: rlaclgns5628

  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        show_sql: 'true'
        format_sql: 'true'
#        use_sql_comments: 'true'

  output:
    ansi:
      enabled: always